### ISSUE TITLE
Error running the example

### ISSUE THREAD

**Issue by DylanC** [vuejs/vue-test-utils-jest-example#13]
> 'cross-env' is not recognized as an internal or external command

appears after running:

`npm run dev`

**Comment by DylanC** [comment]
After running: `npm install cross-env` manually I get this after `npm run dev`:

> 'webpack-dev-server' is not recognized as an internal or external command

**Comment by eddyerburgh** [comment]
Does this solve your issue—https://stackoverflow.com/a/35817969/4939630 ?

**Comment by DylanC** [comment]
@eddyerburgh - I reckon you can ignore this. I reinstalled node and npm yesterday due to multiple issues happening. All my issues disappeared after the reinstall.
