### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by macedigital** [vuejs/vue-test-utils-jest-example#17]
Current babel transform target rules look broken. Running test yields
these error messages:

```txt
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { shallow } from '@vue/test-utils';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:305:17)
          at Generator.next (<anonymous>)
          at new Promise (<anonymous>)
```

I created a PR #16 that fixes the problem. But I'm also curious why not everyone seems to be affected by this issue.

**Comment by eddyerburgh** [comment]
What's your OS, node version, and npm/yarn version?

**Comment by macedigital** [comment]
Sorry for the late reply.

After some digging I came to the conclusion, that this is a 1-in-billion issue due a combination of: 

- `npm run` babel/jest spawning sub-processes
- nodejs not being installed system-wide, but only via `nvm` (so `/usr/bin/env node` stuff doesn't work)
- potentially the "wrong" custom modifications to sh/bash via `.bashrc` / `.bash_profile`

If anyone else is having this issue: Run tests on a machine that provides node and npm "system-wide", e.g. inside a Docker container of `node:carbon-alpine`.

Not sure yet, what exactly the root cause is, but I'm currently running further experiments on 2 different computers with almost the same (software) setup. On one I can run jest tests and the other fails with above message.

If anything, this looks like a nvm/babel/jest-issue, so I'm closing this ticket. 

For reference (on both machines):

```sh
uname -r
# 4.15.9-300.fc27.x64_64

nvm -v
# 0.33.8

node -v
# 8.10.0

npm -v
# 5.6.0

yarn -v
# 1.5.1
```

**Comment by baixiaoji** [comment]
> that provides node and npm "system-wide", e.g. inside a Docker container of node:carbon-alpine.

sorry，what's this mean?  Then, how to solve this issue, i install the same version of you, but having the same err,  and I find the #11  install the `jest-transform-stub`， but it did nothing, and my err message is below 
![image](https://user-images.githubusercontent.com/21168366/39395075-8291c026-4b0c-11e8-8717-18091944540d.png)

**Comment by macedigital** [comment]
@baixiaoji Applying `jest-transform-stub` only works for static assets (like images, css files, etc.). Can you try applying the workaround from https://github.com/vuejs/vue-test-utils-jest-example/pull/16/files ? It might solve the issue for you.
