### ISSUE TITLE
Add links to other examples

### ISSUE THREAD

**Issue by sobolevn** [vuejs/vue-test-utils-jest-example#19]
Maybe we should create a section in the readme with other setups?
There are different use-cases for `jest`: including coverage, extra `babel` and `eslint` plugins, custom assertions, and more stuff that differs from project to project.

Right now I am speaking specifically about https://github.com/wemake-services/wemake-vue-template and its `jest` setup.

Thanks!

**Comment by LinusBorg** [comment]
As the examples is marked as outdated (see README), we're not gonna add new stuff/make changes.
