### ISSUE TITLE
The trigger method can not support mouseover, mouseout, mousedown

### ISSUE THREAD

**Issue by xinchenxin** [vuejs/vue-test-utils-jest-example#24]
wrapper.trigger('mouseover'), it does not work! Any other ways? Thanks!

**Comment by eddyerburgh** [comment]
`trigger supports these events. If you think you have found a bug where `trigger` does not work as expected, please create an issue with a minimal reproduction in the vue-test-utils repo—https://github.com/vuejs/vue-test-utils.
