### ISSUE TITLE
怎么把环境变量传进去cross-env NODE_ENV=production

### ISSUE THREAD

**Issue by fansiyao** [vuejs/vue-test-utils-jest-example#27]

**Comment by eddyerburgh** [comment]
If the question is how to add extra environment variables using cross-env:

`cross-env NODE_ENV=production EXTRA_ENV_VAR=something`

https://www.npmjs.com/package/cross-env

**Comment by LinusBorg** [comment]
As the examples is marked as outdated (see README), we're not gonna add new stuff/make changes.
