### ISSUE TITLE
the whole example broken SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by adamchenwei** [vuejs/vue-test-utils-jest-example#28]
Similiar issue as mentioned here.
https://github.com/vuejs/vue-test-utils/issues/1011

They all pointing to the import statement for @vue/test-utils

<img width="1096" alt="screen shot 2018-10-25 at 10 21 13 am" src="https://user-images.githubusercontent.com/4201698/47507203-bcfc7100-d83f-11e8-8cc7-76ba8db838d2.png">

**Comment by eddyerburgh** [comment]
This is a version mismatch issue. If you use yarn to install (which uses the project lock file), the test code is compiled correctly.

Note that this example is outdated. It's now recommended to scaffold your project with Vue CLI 3 which provides out-of-the-box configurations for unit testing.

**Comment by adamchenwei** [comment]
thanks for the reply
