### ISSUE TITLE
any example to test with vuex & vue-router?

### ISSUE THREAD

**Issue by githubxiaowen** [vuejs/vue-test-utils-jest-example#3]
any example to test with vuex & vue-router?

**Comment by eddyerburgh** [comment]
Not yet, but we could make one

**Comment by robcresswell** [comment]
@eddyerburgh I can pick this up, if you like. Could you assign me?

**Comment by eddyerburgh** [comment]
That would be really useful @robcresswell 🙂

**Comment by karlitos** [comment]
I have problems using **vuex** together with **vue-router**

```javascript
import { createLocalVue } from '@vue/test-utils';
import VueRouter from 'vue-router';

const localVue = createLocalVue();
localVue.use(VueRouter);

...
```
 works fine, but 

```javascript
import { createLocalVue } from '@vue/test-utils';
import VueRouter from 'vue-router';
import Vuex from 'vuex';

const localVue = createLocalVue();
// router first
localVue.use(VueRouter);
// vuex second
localVue.use(Vuex);
```

leads to bunch of errors ending with: **TypeError: undefined is not an object (evaluating 'route.matched')**

Moe interestingly:
```javascript
import { createLocalVue } from '@vue/test-utils';
import Vuex from 'vuex';
import VueRouter from 'vue-router';

const localVue = createLocalVue();
// vuex first
localVue.use(Vuex);
// router second
localVue.use(VueRouter);
```

is working fine 😮 

Is the order of any importance ?

**Comment by eddyerburgh** [comment]
Could you make an issue in vue-test-utils please @karlitos ?

**Comment by robcresswell** [comment]
I've got some work in-progress locally for this btw. Just been slow going with Christmas + holidays.

**Comment by LinusBorg** [comment]
As the examples is marked as outdated (see README), we're not gonna add new stuff/make changes.
