### ISSUE TITLE
MessageToggle component test fails when updating vue-test-utils to beta9

### ISSUE THREAD

**Issue by petrinecp** [vuejs/vue-test-utils-jest-example#7]
Hi, I've tried updating the vue-test-utils package to 1.0.0-beta.9 but the MessageToggle component test starts failing:

`[vue-test-utils]: find did not return Component, cannot call props() on empty Wrapper`

      at throwError (node_modules/vue-test-utils/dist/vue-test-utils.js:11:9)
      at Object.<anonymous> (test/MessageToggle.spec.js:11:29)
I've read that the code for find method has changed a lot in beta9 vuejs/vue-test-utils#305 and that it doesn't find components without a name property. Although the Message componentis **functional** it contains a name property. Do you have any idea what the problem might be?

**Comment by eddyerburgh** [comment]
Thanks for the report. 
beta.9 has a bug with find and shallow. It will be fixed in beta.10.
